from utilidades import isGuerrero,isMago,isPicaro

def talentos_clase (clase_pj,talentos_pj,estilo_combate,pericias_picaro):
    lista_estilo_combate = ["","[Combate con armas grandes]:Cuando saques 1 o 2 en un dado de daño de un ataque que realices con un arma cuerpo a cuerpo que empuñes con las dos manos, puedes volver a tirarlo, pero debes usar el nuevo resultado, incluso si es 1 o 2. El arma debe tener la propiedad «dos manos» o «versátil» para que puedas obtener este beneficio.","[Combate con dos armas]:Cuando luchas con dos armas, puedes añadir tu modificador por característica al daño del segundo ataque.","[Defensa]:Mientras llevas armaduras, recibes un bonificador de +1 a tu CA.","[Duelo]:Cuando solo empuñas un arma cuerpo a cuerpo en una mano, ganas un bonificador de +2 a las tiradas de daño que hagas con ella.","[Protección]:Cuando una criatura que puedas ver ataque a un objetivo que no eres tú y que se encuentre a 5 pies de ti, puedes usar tu reacción para imponerle desventaja en la tirada de ataque. Debes llevar un escudo.","[Tiro al blanco]:Consigues un bonificador de +2 a las tiradas de ataque que hagas con armas a distancia."]
    lista_pericias_picaro = ["Acrobacias", "Atletismo", "Engañar", "Interpretación", "Intimidar", "Investigación", "Juego de manos", "Percepción", "Perspicacia", "Persuasión", "Sigilo","competencia con herramientas de ladrón"]
    if isMago(clase_pj):
        talentos_pj.append("[Libro de conjuros]: Como estudiante de magia arcana, tienes un libro de conjuros que contiene conjuros que muestran los primeros destellos del verdadero poder.")
        talentos_pj.append("[Lanzamiento ritual]: Puedes lanzar cualquier conjuro de mago como si fuera un ritual si tiene la etiqueta «ritual» y si lo tienes en tu libro de conjuros. No necesitas tener el conjuro preparado.")
        talentos_pj.append("[Recuperación arcana]: Has aprendido a recuperar parte de tu energía arcana estudiando tu libro de conjuros. Una vez por día, cuando hagas un descanso breve, puedes recuperar espacios de conjuro. Los espacios de conjuro pueden tener un nivel combinado igual o menor que la mitad de tu nivel de mago (redondeando hacia arriba) y, como máximo, nivel 5. Por ejemplo, si eres un mago de nivel 4, puedes recuperar hasta un valor de dos niveles de espacios de conjuro. Puedes recuperar un espacio de conjuro de nivel 2 o dos espacios de conjuro de nivel 1.")
    if isGuerrero(clase_pj):
        talentos_pj.append("[Tomar aliento]: Dispones de una fuente ilimitada de vitalidad a la que puedes recurrir para protegerte del daño. Durante tu turno, puedes usar una acción adicional para recuperar un número de puntos de golpe igual a 1d10 + tu nivel de guerrero. Una vez usas este rasgo, debes terminar un descanso corto o largo antes de poder usarlo otra vez.")
        talentos_pj.append(lista_estilo_combate[estilo_combate])
    if isPicaro(clase_pj):
        talentos_pj.append("[Ataque furtivo]: Sabes aprovechar la distracción de un enemigo para atacarlo por la espalda. Una vez por turno, puedes infligir daño adicional a una criatura a la que impactes con un ataque si tienes ventaja en la tirada de ataque. El ataque debe usar un arma sutil o a distancia. Este rasgo funciona aunque no tengas ventaja en la tirada de ataque si otro enemigo del objetivo no incapacitado está a menos de 5 pies de él y si tú no tienes desventaja en la tirada de ataque. La cantidad de daño adicional aumenta conforme subes de nivel en esta clase.")
        talentos_pj.append("[Jerga de ladrones]: Durante tu entrenamiento como pícaro, aprendes la jerga de ladrones, una mezcla de dialecto, argot y código secretos que te permite enviar mensajes en una conversación aparentemente normal. Solo otra criatura que conozca la germanía puede entender tales mensajes. Transmitir un mensaje de este tipo cuesta cuatro veces más que decir la misma idea directamente. Además, entiendes una serie de signos y símbolos que se usan para esconder mensajes cortos y sencillos, como si un área es peligrosa o es territorio de un gremio de ladrones, si hay un botín cerca o si las gentes que viven en la zona son presas fáciles u ofrecerán cobijo a un ladrón a la fuga.")
        talentos_pj.append(f"[Pericia]: Tus dos siguientes competencias duplican el bono de competencia al usarse: {lista_pericias_picaro[pericias_picaro[0]]} y {lista_pericias_picaro[pericias_picaro[1]]}.")
    return talentos_pj

